### ISSUE TITLE
Unable to add to a project on Ubuntu

### ISSUE THREAD

**Issue by markbirbeck** [GPMDP/electron-chromecast#25]
I've tried doing `npm install --save electron-chromecast` and I get the following error:

``` shell
> mdns@2.3.3 install /home/mark/Documents/workspace/markbirbeck/sidewinder-viewer/node_modules/mdns
> node-gyp rebuild

make: Entering directory '/home/mark/Documents/workspace/markbirbeck/sidewinder-viewer/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:0:
../src/mdns.hpp:32:20: fatal error: dns_sd.h: No such file or directory
compilation terminated.
```

<details>
  <summary>

Full details with trace</summary>

  <p>

``` shell
> mdns@2.3.3 install /home/mark/Documents/workspace/markbirbeck/sidewinder-viewer/node_modules/mdns
> node-gyp rebuild

make: Entering directory '/home/mark/Documents/workspace/markbirbeck/sidewinder-viewer/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:0:
../src/mdns.hpp:32:20: fatal error: dns_sd.h: No such file or directory
compilation terminated.
dns_sd_bindings.target.mk:143: recipe for target 'Release/obj.target/dns_sd_bindings/src/dns_sd.o' failed
make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
make: Leaving directory '/home/mark/Documents/workspace/markbirbeck/sidewinder-viewer/node_modules/mdns/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-38-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/mark/Documents/workspace/markbirbeck/sidewinder-viewer/node_modules/mdns
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--save" "electron-chromecast"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! mdns@2.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.3.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mdns
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mark/Documents/workspace/markbirbeck/sidewinder-viewer/npm-debug.log
```

  </p>
</details>

After a bit of poking around, the advice that fixed the problem was to [install `libavahi-compat-libdnssd-dev`](https://github.com/npm/npm/issues/9298):

```
sudo apt install -y libavahi-compat-libdnssd-dev
```

I can't think of any cunning way to make this a dependency in 'node world', but it might be worth adding to the documentation.

**Comment by MarshallOfSound** [comment]
It's in the documentation of MDNS which is a declared dependency of `electron-chromecast`.

I'll add a link to the MDNS docs in the README

**Comment by markbirbeck** [comment]
Perfect!
