### ISSUE TITLE
Error when importing electron-chromecast on mac

### ISSUE THREAD

**Issue by ulilicht** [GPMDP/electron-chromecast#51]
Hey there, 

I setted up a basic electron project and I get the following error message when importing `electron-chromecast`. 

I am using a Mac with OSx 10.13.2. Any hints? 

Thank you! 

```
ProtoBuf.js:348 Uncaught DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://cast_channel.proto/'.
    at Object.ProtoBuf.Util.Util.fetch (http://localhost:3000/static/js/bundle.js:31789:29)
    at Object.ProtoBuf.loadProtoFile (http://localhost:3000/static/js/bundle.js:35675:42)
    at Object.<anonymous> (http://localhost:3000/static/js/bundle.js:3236:24)
    at Object../node_modules/castv2/lib/proto.js (http://localhost:3000/static/js/bundle.js:3258:30)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:679:30)
    at fn (http://localhost:3000/static/js/bundle.js:89:20)
    at Object.<anonymous> (http://localhost:3000/static/js/bundle.js:3034:27)
    at Object../node_modules/castv2/lib/client.js (http://localhost:3000/static/js/bundle.js:3165:30)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:679:30)
    at fn (http://localhost:3000/static/js/bundle.js:89:20)
    at Object../node_modules/castv2/index.js (http://localhost:3000/static/js/bundle.js:2939:14)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:679:30)
    at fn (http://localhost:3000/static/js/bundle.js:89:20)
    at Object../node_modules/electron-chromecast/build/cast/_Classes/Session.js (http://localhost:3000/static/js/bundle.js:5486:14)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:679:30)
    at fn (http://localhost:3000/static/js/bundle.js:89:20)
    at Object.<anonymous> (http://localhost:3000/static/js/bundle.js:5920:16)
    at Object../node_modules/electron-chromecast/build/cast/index.js (http://localhost:3000/static/js/bundle.js:6156:30)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:679:30)
    at fn (http://localhost:3000/static/js/bundle.js:89:20)
    at Object.<anonymous> (http://localhost:3000/static/js/bundle.js:7435:13)
    at Object../node_modules/electron-chromecast/build/index.js (http://localhost:3000/static/js/bundle.js:7482:30)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:679:30)
    at fn (http://localhost:3000/static/js/bundle.js:89:20)
    at Object../src/App.js (http://localhost:3000/static/js/bundle.js:71971:78)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:679:30)
    at fn (http://localhost:3000/static/js/bundle.js:89:20)
    at Object../src/index.js (http://localhost:3000/static/js/bundle.js:72118:63)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:679:30)
    at fn (http://localhost:3000/static/js/bundle.js:89:20)
    at Object.0 (http://localhost:3000/static/js/bundle.js:72268:18)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:679:30)
    at ./node_modules/ansi-regex/index.js.module.exports (http://localhost:3000/static/js/bundle.js:725:37)
    at http://localhost:3000/static/js/bundle.js:728:10
```

```
index.js:2177 ./node_modules/protobufjs/dist/ProtoBuf.js
Module not found: `/Users/ulilicht/Develop/radiocast/node_modules/protobufjs/node_modules/ByteBuffer/dist/ByteBufferAB.js` does not match the corresponding path on disk `bytebuffer`.
__stack_frame_overlay_proxy_console__ @ index.js:2177
```
```
index.js:2177 ./node_modules/protobufjs/node_modules/bytebuffer/dist/ByteBufferAB.js
Module not found: `/Users/ulilicht/Develop/radiocast/node_modules/protobufjs/node_modules/Long/dist/Long.js` does not match the corresponding path on disk `long`.
__stack_frame_overlay_proxy_console__ @ index.js:2177
```

**Comment by jostrander** [comment]
Seems odd, do you have a code example?
